2024-10-29 14:48:33.621939: Login failed: HTTPSConnectionPool(host='datasales.ipboxcloud.com.br', port=9387): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E5ABAF6D0>, 'Connection to datasales.ipboxcloud.com.br timed out. (connect timeout=None)'))
2024-10-29 14:48:33.621939: Login failed: HTTPSConnectionPool(host='datasales.ipboxcloud.com.br', port=9387): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E5ABADC00>, 'Connection to datasales.ipboxcloud.com.br timed out. (connect timeout=None)'))
2024-10-29 14:49:40.447157: Login failed: HTTPSConnectionPool(host='datasales.ipboxcloud.com.br', port=9387): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E599EBBB0>, 'Connection to datasales.ipboxcloud.com.br timed out. (connect timeout=None)'))
2024-10-29 14:50:01.780522: Login failed: HTTPSConnectionPool(host='datasales.ipboxcloud.com.br', port=9387): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E5A71B5B0>, 'Connection to datasales.ipboxcloud.com.br timed out. (connect timeout=None)'))
